config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'jobs#index'

  resources :jobs

  namespace :admin do
    resources :jobs
  end
end

app/models/add_more_detail_to_job.rb
class AddMoreDetailToJob < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/delete_table.rb
class DeleteTable < ApplicationRecord
end

app/models/job.rb
class Job < ApplicationRecord
  validates :wage_upper_bound, presence: true
  validates :wage_lower_bound, presence: true
  validates :wage_lower_bound, numericality: { greater_than: 0}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def admin?
    is_admin
  end 
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]
  before_action :require_is_admin

  def index
    @jobs = Job.all
  end

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
  end

  def require_is_admin
    if !current_user.admin?
      flash[:alert] = 'You are not admin.'
      redirect_to root_path
    end
  end

  def require_is_admin
    if current_user.admin?
      flash[:alert] = 'You are not admin'
      redirect_to root_path
    end
  end


  private

  def job_params
    params.require(:job).permit(:title, :descrption, :wage_upper_bound, :wage_lower_bound, :contact_email, :is_hidden)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :update, :eidt, :destroy]

  def index
    @jobs = Job.where(:is_hidden => false).order("created_at DESC")
  end

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to jobs_path
    else
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to jobs_path
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to
  end



  private

  def job_params
    params.require(:job).permit(:title, :description, :wage_upper_bound, :wage_lower_bound, :contact_email, :is_hidden)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    flash[:notice] = "你好！欢迎来到 Learners"
  end
end

app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/jobs_helper.rb
module JobsHelper

  def render_job_status(job)
    if job.is_hidden
      "(Hidden)"
    else
      "(Public)"
    end
  end 
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/jobs/edit.html.erb
<h1> Edit a job </h1>

<%= simple_form_for [:admin, @job ] do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :wage_lower_bound, :label => "薪资下限" %>
<%= f.input :wage_upper_bound, :label => "薪资上限" %>
<%= f.input :contact_email %>
<%= f.input :is_hidden %>

  <%= f.submit "Submit" %>
<% end %>

app/views/admin/jobs/index.html.erb
<div class="pull-right">
  <%= link_to("Add a job", new_admin_job_path, :class => "btn btn-default" ) %>
</div>

<br><br>

<table class="table table-bordered">
  <% @jobs.each do |job| %>
  <tr>
    <td>
      <%= render_job_status(job) %>
      <%= link_to(job.title, admin_job_path(job)) %>
    </td>
    <td>
      <%= link_to("Edit", edit_admin_job_path(job)) %>
      <%= link_to("Destroy", admin_job_path(job), :method => :delete, :data => { :confirm => "Are you sure?" }) %>
    </td>
    <td>
      <%= job.created_at %>
    </td>

  </tr>
  <% end %>
</table>

app/views/admin/jobs/new.html.erb
<h1> Add a job </h1>

<%= simple_form_for [:admin,@job] do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :wage_lower_bound, :label => "薪资下限" %>
<%= f.input :wage_upper_bound, :label => "薪资上限" %>
<%= f.input :contact_email %>
<%= f.input :is_hidden %>

  <%= f.submit "Submit" %>
<% end %>

app/views/admin/jobs/show.html.erb
<h1> <%= @job.title %> </h1>

<p>
  <%= simple_format(@job.description) %>

</p>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2019 Learner.wiki
        <br>Design by
        <a href="http://learner.wiki" target=_new>Learner</a>
    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Learner</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                               <% if !current_user %>
                   <li><%= link_to("注册", new_user_registration_path) %> </li>
                   <li><%= link_to("登入", new_user_session_path) %></li>
                 <% else %>
                   <li class="dropdown">
                     <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                         Hi!, <%= current_user.email %>
                         <b class="caret"></b>
                     </a>
                     <ul class="dropdown-menu">
                         <li> <%= link_to("Admin Panel", admin_jobs_path)%> </li>
                         <li> <%= link_to("登出", destroy_user_session_path, method: :delete) %> </li>
                     </ul>
                   </li>
                 <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/jobs/edit.html.erb
<h1> Edit a job </h1>

<%= simple_form_for @job do |f| %>
<%= f.input :title %>
<%= f.input :description %>
<%= f.input :wage_lower_bound, :label => "薪资下限" %>
<%= f.input :wage_upper_bound, :label => "薪资上限" %>
<%= f.input :contact_email %>
<%= f.input :is_hidden %>
<%= f.submit "Submit" %>
<% end %>

app/views/jobs/index.html.erb
<table class="table table-bordered">

  <div class="pull-right">
    <%= link_to("Add a job", new_job_path, :class => "btn btn-default") %>
  </div>

  <% @jobs.each do |job| %>
  <tr>
    <td>
      <%= link_to(job.title, job_path(job)) %>
    </td>
    <td>
      <%= link_to("Edit", edit_job_path(job))%> |
      <%= link_to("destroy", job_path(job), :method => :delete, :data => { :confirm => "Are you sure?"})%>
    </td>
    <td>
      <%= job.created_at%>
    </td>
  </tr>
  <% end %>
</table>

app/views/jobs/new.html.erb
<h1> Add a job </h1>
<%= simple_form_for @job do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :wage_lower_bound, :label => "薪资下限" %>
<%= f.input :wage_upper_bound, :label => "薪资上限" %>
<%= f.input :contact_email %>
<%= f.input :is_hidden %>


<%= f.submit "Submit" %>
<% end %>

app/views/jobs/show.html.erb
<h1><%= @job.title %></h1>
<h1><%= @job.description %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Learner</title>
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>
    <body>
        <div class="container-fluid">
            <%= render "common/navbar" %>
            <%= render "common/flashes" %>
            <%= yield %>
        </div>
        <%= render "common/footer" %>
    </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello learner!</h1>